# yaml-language-server: $schema=https://raw.githubusercontent.com/oapi-codegen/oapi-codegen/HEAD/configuration-schema.json
package: simulator
generate:
  client: true
output: ./gen/simulator/client.go
