# yaml-language-server: $schema=https://raw.githubusercontent.com/oapi-codegen/oapi-codegen/HEAD/configuration-schema.json
package: simulator
generate:
  models: true
  server-urls: true
output: ./gen/simulator/models.go
