# yaml-language-server: $schema=https://raw.githubusercontent.com/oapi-codegen/oapi-codegen/HEAD/configuration-schema.json
package: simulator
generate:
  fiber-server: true
output: ./gen/simulator/server.go
