services:
  docker-cleanup:
    image: docker:latest
    command: >
      sh -c "while true; do
        docker container prune -f;
        sleep 600;
      done"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: global
      restart_policy:
        condition: any
     

  gateway-server:
    image: cyber-navigate/gateway-server
    depends_on:
      - article-service
    ports:
      - target: 443
        published: 9443
        protocol: tcp
        mode: host
      - target: 80
        published: 9080
        protocol: tcp
        mode: host
        
  mongo:
    image: cyber-navigate/mongo
    ports:
      - target: 27017
        published: 27017
        protocol: tcp
        mode: host
    secrets:
      - source: mongo_secret
        target: mongo_secret
    deploy:
      replicas: 1
    volumes:
      - mongo_data:/data/db

  postgres:
    image: cyber-navigate/postgres
    ports:
      - target: 5432
        published: 5777
        protocol: tcp
        mode: host
    volumes:
      - postgres_data:/var/lib/postgresql/
    secrets:
      - source: postgres_secret
        target: postgres_secret
    deploy:
      replicas: 1

  article-service:
    image: cyber-navigate/article-service
    secrets:
      - source: article_service_secret
        target: article_service_secret

    depends_on:
      - postgres
      - mongo
  user-service:
    image: cyber-navigate/user-service
    secrets:
      - source: user_service_secret
        target: user_service_secret

    depends_on:
      - postgres
 
    


volumes:
  mongo_data:
  postgres_data:
    driver: local


secrets:
  postgres_secret:
    external: true
  mongo_secret:
    external: true
  article_service_secret:
    external: true
  user_service_secret:
    external: true