server {
    listen 80;
    server_name  xn----8sbabhgkwfn1brsi2a.xn--p1ai api.xn----8sbabhgkwfn1brsi2a.xn--p1ai www.xn----8sbabhgkwfn1brsi2a.xn--p1ai;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

