syntax = "proto3";

import "google/api/annotations.proto";
import "google/protobuf/empty.proto";

package article;

option go_package = "neknb.article.v1;articlev1";

//
service Articles {
	//
  rpc Create (CreateArticleRequest) returns (ArticleStatusResponse) {
    option (google.api.http) = {
      post: "/api/v1/articles/create",
      body: "*",
    };
  };

	// Используется для запроса к конкретной статье. 
  // Не подходит для реализации поиска.
  //  В случае отсутсвия ресурса в базе возвращает огибку
  rpc GetArticle (GetArticleRequest) returns (ArticleStatusResponse) {
    option (google.api.http) = {
      get: "/api/v1/articles/{article_id}",
    };
  };

  // Выполняет потоковую передачу текста статьи
  rpc GetArticleTextStream (GetArticleRequest) returns (stream ArticleChunk) {
    option (google.api.http) = {
      get: "/api/v1/articles/{article_id}/text",
    };
  };

	//
  rpc GetArticles (google.protobuf.Empty) returns (ArticlesListResponse) {
    option (google.api.http) = {
      get: "/api/v1/articles"
    };
  };

	//
  rpc Update (ArticleUpdateRequest) returns (ArticleStatusResponse) {
    option (google.api.http) = {
      patch:  "/api/v1/articles/{article_id}",
			body: "*",
    };
  };
}

// Create
message CreateArticleRequest {
  string article_name = 1;
}

// 
message ArticleStatusResponse {
	string article_uuid =1;
	string article_name = 2;
	string article_status = 3;
}

//
message GetArticleRequest {
	string article_id = 1;
}

//
message ArticlesListResponse {
	int64 total = 1;
	repeated Article articles =2;
}

//
message Article {
	string title = 1;
	string text = 2;
	optional string video_link = 3;
}

// 
message ArticleChunk {
  bytes content = 1;
}

// 
message ArticleUpdateRequest {
	string article_id = 1;
	optional string title = 2;
  optional string text = 3;
  optional string video_link = 4;
}