env: "dev"

server:
  host: 0.0.0.0
  http_port: 80
  https_port: 443

  services:
    - article-service:
        path: /api/v1/articles
        protocol: https
        host: cyber-navigate_article-service
        port: 8000
    - user-service:
        path: /api/v1/users
        protocol: https
        host: cyber-navigate_user-service
        port: 8000
    - user-service:
        path: /api/v1/auth
        protocol: https
        host: cyber-navigate_user-service
        port: 8000

public_key_path: ./keys/public.pem

certs:
  ca_cert: /certs/ca-cert.pem

  client_cert: /certs/client-cert.pem
  client_key: /certs/client-key.pem

  public_cert: /certs/public-cert.pem
  public_key: /certs/public-key.pem
