env: "dev"

server:
  port: 9000
  services:
    - article:
        path: /api/v1/articles
        protocol: http
        host: cyber-navigate_article-service
        port: 8000
    - user:
        path: /api/v1/users
        protocol: http
        host: cyber-navigate_user-service
        port: 8000
    - auth:
        path: /api/v1/auth
        protocol: http
        host: cyber-navigate_user-service
        port: 8000
