# HTTP сервер для получения сертификата Let's Encrypt
server {
    listen 80;
    server_name api.кибер-навигатор.рф www.кибер-навигатор.рф;

    # Путь, который проверяет Certbot
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    # Временно редиректим весь остальной трафик тоже на корень certbot,
    # либо просто возвращаем 404, пока нет сертификатов
    location / {
        return 404;
    }
}