openapi: "3.0.3"
info:
  title: API CyberNavigate
  version: "1.0"
servers:
  - url: http://localhost:9000/api/v1
    description: Local API Gateway Server
  - url: http://127.0.0.1:9000/api/v1
    description: Local API Gateway Server
  - url: http://127.0.0.1:8000/api/v1
    description: Local Service
  - url: http://cyber-navigate_gateway-server/api/v1
    description: Internal Docker API Gateway Server

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

paths:
  /:
