openapi: 3.2.0

info:
  title: API CyberNavigate
  version: "1.0"
  description: |
    API сервиса пользователей с авторизацией по username/password.
    Аутентификация реализована через access и refresh JWT токены.
servers:
  - url: http://localhost:9000/api/v1
    description: Local API Gateway Server
  - url: http://127.0.0.1:9000/api/v1
    description: Local API Gateway Server
  - url: http://127.0.0.1:8000/api/v1
    description: Local Service
  - url: http://cyber-navigate_gateway-server/api/v1
    description: Internal Docker API Gateway Server
security:
  - BearerAuth: []

tags:
  - name: User
    description: Ручки для пользователей
  - name: Admin
    description: Ручки для администраторов

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  requestBodies:
    InputStepRequest:
      required: true
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/StepMeta"

  responses:
    BadRequestResponse:
      description: Bad Request - Invalid request parameters or body
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"
          example:
            message: "Invalid data"

    ForbiddenResponse:
      description: Forbidden - You don't have permission to access this resource
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"
          example:
            message: "Insufficient permissions to perform this action"

    UnauthorizedResponse:
      description: Unauthorized - Authentication is required or token is invalid/expired
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"
          example:
            message: "Missing or invalid authentication token"

    NotFoundResponse:
      description: Not Found - Requested resource does not exist
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"
          example:
            message: "Resource with id not found"

    UnprocessableEntityResponse:
      description: Unprocessable Entity - Validation failed
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"
          example:
            message: "Validation failed: some fields is required"

    ScenarioResponse:
      description: Сценарий
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ScenarioFull"

    StepMetaRespose:
      description: Шаг с Метаданными
      content:
        appliaction/json:
          schema:
            allOf:
              - $ref: "#/components/schemas/BaseId"
              - $ref: "#/components/schemas/StepMeta"

  schemas:
    BaseId:
      type: object
      required: ["id"]
      properties:
        id:
          type: string
          format: uuid
          example: 2b1c6d2c-4e6f-4c9b-a2b4-8f1d2c3e4f5a

    ErrorResponse:
      type: object
      required:
        - message
      properties:
        message:
          type: string

    ScenarioBase:
      type: object
      required: [difficulty, title, description]
      properties:
        difficulty:
          type: string
          enum:
            - easy
            - middle
            - hard
          example: easy
        title:
          type: string
          example: first scenatio
        description:
          type: string
          example: about our scenario
        articleIds:
          type: array
          items:
            type: string
            format: uuid
            example: 2b1c6d2c-4e6f-4c9b-a2b4-8f1d2c3e4f5a

    ScenarioFull:
      allOf:
        - $ref: "#/components/schemas/BaseId"
        - $ref: "#/components/schemas/ScenarioBase"

    StepBase:
      required: ["actions"]
      allOf:
        - $ref: "#/components/schemas/BaseId"
        - type: object
          properties:
            actions:
              type: array
              items:
                $ref: "#/components/schemas/Action"

    StepMeta:
      type: object
      properties:
        scenarioId:
          type: string
          format: uuid
          example: 2b1c6d2c-4e6f-4c9b-a2b4-8f1d2c3e4f5a
        previousStep:
          type: string
          format: uuid
          example: 2b1c6d2c-4e6f-4c9b-a2b4-8f1d2c3e4f5a
        previosAnswer:
          type: string
          format: uuid
          example: 2b1c6d2c-4e6f-4c9b-a2b4-8f1d2c3e4f5a
        minTrust:
          type: integer
          example: 0
        maxTrust:
          type: integer
          example: 3
        actions:
          type: array
          items:
            $ref: "#/components/schemas/Action"

    Action:
      type: object
      properties:
        type:
          type: string
          enum: [message, sms]
        object:
          oneOf:
            - $ref: "#/components/schemas/MessageObject"
            - $ref: "#/components/schemas/SmsObject"
          discriminator:
            propertyName: type
            mapping:
              message: "#/components/schemas/MessageObject"
              sms: "#/components/schemas/SmsObject"
            defaultMapping: "#/components/schemas/MessageObject"
        delay:
          type: integer
          example: 10

    SmsObject:
      type: object
      properties:
        type:
          type: string
          example: sms
        sender:
          type: string
          example: Коля
        text:
          type: string
          example: Привет Друг!

    FileObject:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: 2b1c6d2c-4e6f-4c9b-a2b4-8f1d2c3e4f5a
        filename:
          type: string
          example: game.apk
        isSafe:
          type: boolean
          example: false
        size:
          type: integer
          example: 10

    MessageObject:
      type: object
      properties:
        senderName:
          type: string
          example: Коля
        senderId:
          type: string
          format: uuid
          example: 2b1c6d2c-4e6f-4c9b-a2b4-8f1d2c3e4f5a
        text:
          type: string
          example: Привет Друг!
        filename:
          type: string
          example: game.apk
        fileId:
          type: string
          format: uuid
          example: 2b1c6d2c-4e6f-4c9b-a2b4-8f1d2c3e4f5a
        answers:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
                format: uuid
                example: 2b1c6d2c-4e6f-4c9b-a2b4-8f1d2c3e4f5a
              text:
                type: string
                example: Привет Друг!
              trust:
                type: integer
                example: -10

paths:
  /simulator/scenarios:
    get:
      x-auth:
        public: true
        permission: user
      security: []
      tags:
        - User
      summary: Получить список доступных сценариев
      operationId: getAllScenarios
      responses:
        "200":
          description: Список всех доступных пользователю сценариев
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ScenarioFull"

    post:
      x-auth:
        public: false
        permission: admin
      parameters:
        - name: X-User-Id
          in: header
          required: true
          schema:
            type: string
            format: uuid
      tags:
        - Admin
      summary: Создание нового сценария
      operationId: createScenario
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ScenarioBase"

      responses:
        "201":
          description: Сценарий создан
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ScenarioFull"
        "401":
          $ref: "#/components/responses/UnauthorizedResponse"
        "403":
          $ref: "#/components/responses/ForbiddenResponse"
        "422":
          $ref: "#/components/responses/UnprocessableEntityResponse"

  /simulator/scenarios/{scenarioId}:
    get:
      x-auth:
        public: true
        permission: user
      tags:
        - User
      security: []
      parameters:
        - name: scenarioId
          in: path
          description: ID of scenario
          required: true
          schema:
            type: string
      summary: Получить Сценарий по Id
      operationId: getScenarioById
      responses:
        "200":
          description: Информация о всех сценариях
          $ref: "#/components/responses/ScenarioResponse"
        "404":
          description: Сценарий не найден
          $ref: "#/components/responses/NotFoundResponse"

    patch:
      x-auth:
        public: false
        permission: admin

      tags:
        - Admin
      summary: Обновленние данных сценария
      operationId: editScenario
      parameters:
        - name: X-User-Id
          in: header
          required: true
          schema:
            type: string
            format: uuid
        - name: scenarioId
          in: path
          description: ID of scenario
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ScenarioBase"
      responses:
        "200":
          description: Сценарий обновлен
          $ref: "#/components/responses/ScenarioResponse"
        "404":
          description: Сценарий не найден
          $ref: "#/components/responses/NotFoundResponse"
        "403":
          $ref: "#/components/responses/ForbiddenResponse"
        "401":
          $ref: "#/components/responses/UnauthorizedResponse"
        "422":
          $ref: "#/components/responses/UnprocessableEntityResponse"

  /simulator/step:
    get:
      x-auth:
        public: false
        permission: user
      parameters:
        - name: X-User-Id
          in: header
          required: true
          schema:
            type: string
            format: uuid
      tags:
        - User
      summary: Получить Шаг
      operationId: getStep
      responses:
        "200":
          description: Информация о шаге
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StepBase"
        "401":
          $ref: "#/components/responses/UnauthorizedResponse"

    post:
      x-auth:
        public: false
        permission: admin
      parameters:
        - name: X-User-Id
          in: header
          required: true
          schema:
            type: string
            format: uuid
      tags:
        - Admin
      summary: Создание нового шага
      operationId: createStep
      requestBody:
        $ref: "#/components/requestBodies/InputStepRequest"
      responses:
        "201":
          $ref: "#/components/responses/StepMetaRespose"
        "400":
          $ref: "#/components/responses/BadRequestResponse"
        "401":
          $ref: "#/components/responses/UnauthorizedResponse"
        "403":
          $ref: "#/components/responses/ForbiddenResponse"
        "422":
          $ref: "#/components/responses/UnprocessableEntityResponse"

  /simulator/step/{stepId}:
    put:
      x-auth:
        public: false
        permission: admin
      parameters:
        - name: stepId
          in: path
          required: true
          schema:
            type: string
        - name: X-User-Id
          in: header
          required: true
          schema:
            type: string
            format: uuid
      tags:
        - Admin
      summary: Обновление шага
      operationId: updateStep
      requestBody:
        $ref: "#/components/requestBodies/InputStepRequest"
      responses:
        "200":
          $ref: "#/components/responses/StepMetaRespose"
        "400":
          $ref: "#/components/responses/BadRequestResponse"
        "401":
          $ref: "#/components/responses/UnauthorizedResponse"
        "403":
          $ref: "#/components/responses/ForbiddenResponse"
        "404":
          $ref: "#/components/responses/NotFoundResponse"
        "422":
          $ref: "#/components/responses/UnprocessableEntityResponse"
  /simulator/action/file/{fileId}:
    get:
      x-auth:
        public: false
        permission: user
      tags:
        - User
      parameters:
        - name: fileId
          in: path
          required: true
          schema:
            type: string
        - name: X-User-Id
          in: header
          required: true
          schema:
            type: string

      summary: Получить файл по Id
      operationId: getFileByFileId
      responses:
        "200":
          description: Информация о файле
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FileObject"
        "401":
          $ref: "#/components/responses/UnauthorizedResponse"
        "404":
          description: файл не найден
          $ref: "#/components/responses/NotFoundResponse"

  /simulator/action/answer:
    post:
      x-auth:
        public: false
        permission: user
      parameters:
        - name: X-User-Id
          in: header
          required: true
          schema:
            type: string

      tags:
        - User
      summary: Отправка ответа пользователя
      operationId: sendAnswer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                answerId:
                  type: string
                  format: uuid
                  example: 2b1c6d2c-4e6f-4c9b-a2b4-8f1d2c3e4f5a
      responses:
        "204":
          description: Ответ обработан
        "400":
          description: Неверный answerId
          $ref: "#/components/responses/BadRequestResponse"
        "401":
          $ref: "#/components/responses/UnauthorizedResponse"
        "422":
          $ref: "#/components/responses/UnprocessableEntityResponse"

  # ======================================
  #       СЕССИЯ ИГРЫ
  # ======================================
  /simulator/start:
    post:
      x-auth:
        public: false
        permission: user
      parameters:
        - name: X-User-Id
          in: header
          required: true
          schema:
            type: string
      tags:
        - User
      summary: Создает сессию симулятора
      operationId: createSimulatorSession
      responses:
        "204":
          description: Сессия создана
        "400":
          description: Сессия была создана ранее
          $ref: "#/components/responses/BadRequestResponse"
        "401":
          $ref: "#/components/responses/UnauthorizedResponse"
        "422":
          $ref: "#/components/responses/UnprocessableEntityResponse"
  /simulator/final:
    get:
      x-auth:
        public: false
        permission: user
      parameters:
        - name: X-User-Id
          in: header
          required: true
          schema:
            type: string
      tags:
        - User
      summary: Запрашивает результаты игры
      operationId: getResults
      responses:
        "200":
          description: Результат игры
          content:
            application/json:
              schema:
                type: object
                properties:
                  gameDuration:
                    type: integer
                    example: 15
                  errors:
                    type: array
                    items:
                      type: string
                      example: Нельзя называть маме номер банковской карточки
                  trustGraph:
                    type: array
                    items:
                      type: integer
                    example: [2, 3]

        "401":
          $ref: "#/components/responses/UnauthorizedResponse"
        "422":
          $ref: "#/components/responses/UnprocessableEntityResponse"
