# yaml-language-server: $schema=https://raw.githubusercontent.com/oapi-codegen/oapi-codegen/HEAD/configuration-schema.json
package: article
generate:
  models: true
  server-urls: true
output: ./gen/article/models.go
