env: "local" # dev, prod

http:
  port: 8000
  timeout: 10h

storages:
  postgres:
    database: user_service_db
    host: cyber-navigate_postgres
    port: 5432
    user: user_service_role
tokens:
  access:
    expiration: 900 # 15 минут

  refresh:
    expiration: 2592000 # 30 дней

private_key_path: ../keys/private.pem
public_key_path: ../keys/public.pem
