env: "dev"

http:
  port: 8000
  timeout: 10h

storages:
  postgres:
    database: article_service_db
    host: cyber-navigate_postgres
    port: 5432
    user: article_service_role

  mongo:
    database: article-storage
    host: cyber-navigate_mongo
    port: 27017
    user: articleService
    collection: articles

certs:
  ca_cert: certs/ca-cert.pem

  server_cert: ./certs/server-cert.pem
  server_key: ./certs/server-key.pem
