env: "local" # dev, prod

http:
  port: 8000
  timeout: 10h

storages:
  postgres:
    database: article_service_db
    host: localhost
    port: 5777
    user: article_service_role

  mongo:
    database: article-storage
    host: localhost
    port: 27017
    user: articleService
    collection: articles

certs:
  ca_cert: ../../secrets/certs/article-service/ca-cert.pem

  server_cert: ../../secrets/certs/article-service/server-cert.pem
  server_key: ../../secrets/certs/article-service/server-key.pem
