env: "local" # dev, prod

http:
  port: 9000
  timeout: 10h

storages:
  postgres:
    database: article_service_db
    host: localhost
    port: 5777
    user: article_service_role

  mongo:
    database: article-storage
    host: localhost
    port: 27017
    user: articleService
    collection: articles
