openapi: "3.0.3"
info:
  title: API CyberNavigate
  version: "1.0"
servers:
  - url: http://localhost:9000/api/v1
    description: Local API Gateway Server
  - url: http://cyber-navigate_gateway/api/v1
    description: Internal Docker API Gateway Server

components:
  schemas:
    ArticleMetaData:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        status:
          type: string
      example:
        id: "0c0ea3c4-925e-4801-9ef5-b6c40976d3c0"
        title: "Article Title 1"
        status: "draft"

paths:
  /articles:
    post:
      summary: Create article with articleName
      tags:
        - Admin
      requestBody:
        required: true
        description: Create Article Entity Request
        content:
          application/json:
            schema:
              type: object
              properties:
                articleTitle:
                  type: string
                  example: "Article Title"
      responses:
        "201":
          description: ArticleMetaData
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ArticleMetaData"
    get:
      summary: Get All Articles Entity
      tags:
        - User
      responses:
        "200":
          description: List of ArticleMetaData
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ArticleMetaData"

  /articles/{articleId}:
    patch:
      tags:
        - Admin
      summary: Update article by Id
      parameters:
        - name: articleId
          in: path
          description: ID of article
          required: true
          schema:
            type: string
      requestBody:
        required: true
        description: Create Article Entity Request
        content:
          application/json:
            schema:
              type: object
              properties:
                articleTitle:
                  type: string
                  example: "Article Title"
                articleStatus:
                  type: string
                  example: "published"

      responses:
        "200":
          description: ArticleMetaData
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ArticleMetaData"

    get:
      tags:
        - User
      summary: Find article by Id
      operationId: getPetsById
      responses:
        "200":
          description: pet response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ArticleMetaData"
    parameters:
      - name: articleId
        in: path
        description: ID of article
        required: true
        schema:
          type: string

  /articles/{articleId}/text:
    post:
      tags:
        - Admin
      summary: Upload Article Text by articleId
      parameters:
        - name: articleId
          in: path
          description: ID of article
          required: true
          schema:
            type: string
      requestBody:
        content:
          text/plain:
            schema:
              type: string
      responses:
        "200":
          description: "Success"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ArticleMetaData"

    get:
      tags:
        - User
      summary: Article Text By articleId
      parameters:
        - name: articleId
          in: path
          description: ID of article
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Stream of article text (NDJSON)
          content:
            application/x-ndjson:
              schema:
                type: string
                format: binary
